# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb12ce41d10f5abe677567799918d8ed17cc9c1ce2e970c2d640ed2d0b3905197ee9dead951c1f741dbef778088a952b82fad223cd008830f5dbf5f23b700ab3

test:
  secret_key_base: 7b77b1930aa1f3bfefcc757bbde461dc4c3cce7ed12e5ef9ada9838afac06746389e13bd229d28b063e6a376034f7f883e9a747e07e6fac0193c47a9a331b188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
